# Generated by Django 6.1 on 2026-09-01 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('subscription', 'Subscription')], max_length=30)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile money'), ('card', 'Card')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('internal_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='iotec', max_length=30)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('redirect_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('sent_to_vendor', 'Sent to vendor'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('requires_review', 'Requires review'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('subscription_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_payment', to='subscriptions.subscriptionpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('credit', 'Credit (platform received)'), ('debit', 'Debit (platform paid out)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_payload', models.JSONField()),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('processing_notes', models.CharField(blank=True, max_length=255)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['user', 'created_at'], name='payments_le_user_id_38c09d_idx'),
        ),
    ]
