# Generated by Django 6.1 on 2026-09-06 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('rider_earnings', 'Rider earnings')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone', models.CharField(max_length=20)),
                ('internal_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='iotec', max_length=30)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Sent to vendor'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_payload', models.JSONField()),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('processing_notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentcallback',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='paymentcallback',
            index=models.Index(fields=['payment', 'provider_status', 'provider_transaction_id'], name='payments_pa_payment_4babaf_idx'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalcallback',
            name='withdrawal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='payments.withdrawal'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status'], name='payments_wi_user_id_8ab084_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status', 'created_at'], name='payments_wi_status_eb5158_idx'),
        ),
    ]
