# Generated by Django 6.1 on 2026-09-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_withdrawal_withdrawalcallback_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='promotion_purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_payment', to='promotions.promotionpurchase'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('promotion', 'Offer promotion')], max_length=30),
        ),
    ]
