# Generated by Django 6.1 on 2026-09-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('payments_view', 'Can view payments'), ('payments_refund', 'Can refund payments'), ('payments_settle', 'Can settle payments'), ('withdrawals_approve', 'Can approve withdrawals'), ('withdrawals_reverse', 'Can reverse withdrawals'), ('users_suspend', 'Can suspend/reactivate user accounts'), ('merchant_verify', 'Can verify merchants'), ('rider_verify', 'Can verify riders'), ('agent_manage', 'Can onboard/manage agents'), ('fees_manage', 'Can manage platform fees'), ('settings_manage', 'Can manage platform settings'), ('reports_view', 'Can view admin reports')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
