# Generated by Django 6.1 on 2026-10-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_riskevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincapability',
            options={'default_permissions': (), 'managed': False, 'permissions': [('payments_view', 'Can view payments'), ('payments_refund', 'Can refund payments'), ('payments_settle', 'Can settle payments'), ('withdrawals_approve', 'Can approve withdrawals'), ('withdrawals_reverse', 'Can reverse withdrawals'), ('users_suspend', 'Can suspend/reactivate user accounts'), ('merchant_verify', 'Can verify merchants'), ('rider_verify', 'Can verify riders'), ('agent_manage', 'Can onboard/manage agents'), ('fees_manage', 'Can manage platform fees'), ('settings_manage', 'Can manage platform settings'), ('reports_view', 'Can view admin reports'), ('offers_moderate', 'Can approve/reject/pause offers'), ('notifications_broadcast', 'Can send notifications to groups of users'), ('content_manage', 'Can manage areas, categories, pickup points and agent tasks')]},
        ),
    ]
