# Generated by Django 6.1 on 2026-09-01 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('members', '0001_initial'),
        ('merchants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('member_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saving_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='savings_record', to='claims.offerclaim')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_records', to='members.member')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_records', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'created_at'], name='savings_sav_member__fe4c73_idx')],
            },
        ),
    ]
