# Generated by Django 6.1 on 2026-08-31 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='offers.offercategory'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantdocument',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='merchantdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantverification',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='merchantverification',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_verifications_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['area', 'status'], name='merchants_m_area_id_61d41b_idx'),
        ),
    ]
