# Generated by Django 6.1 on 2026-08-31 11:36

import django.core.validators
import django.db.models.deletion
import offers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Offer categories',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=150)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('member_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('pickup_location', models.CharField(blank=True, max_length=255)),
                ('delivery_available', models.BooleanField(default=False)),
                ('offer_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('packaging_status', models.CharField(choices=[('unspecified', 'Not specified'), ('sealed', 'Sealed / factory packaging'), ('repackaged', 'Repackaged by merchant'), ('loose', 'Loose / unpackaged')], default='unspecified', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('paused', 'Paused'), ('rejected', 'Rejected'), ('reported', 'Reported'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('visibility_score', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.area')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='merchants.merchant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='offers.offercategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='offers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), offers.models.validate_image_size])),
                ('is_primary', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.offer')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('view', 'View'), ('call', 'Call'), ('whatsapp', 'WhatsApp'), ('delivery_request_click', 'Delivery request click')], max_length=30)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='offers.offer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'expires_at'], name='offers_offe_status_f98e70_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['area', 'category', 'status'], name='offers_offe_area_id_2998c1_idx'),
        ),
        migrations.AddIndex(
            model_name='offerinteraction',
            index=models.Index(fields=['offer', 'kind', 'created_at'], name='offers_offe_offer_i_200e04_idx'),
        ),
    ]
