# Generated by Django 6.1 on 2026-10-02 02:28

import core.uploads
import django.core.validators
import riders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderdocument',
            name='file',
            field=models.FileField(storage=core.uploads.private_storage, upload_to='rider_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), riders.models.validate_document_size]),
        ),
    ]
