# Generated by Django 6.1 on 2026-09-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_riskevent'),
        ('members', '0002_referralreward'),
        ('merchants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Has responses'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='open', max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.area')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_responses', to='merchants.merchant')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='item_requests.memberrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('request', 'merchant')},
            },
        ),
        migrations.AddField(
            model_name='memberrequest',
            name='fulfilled_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='item_requests.requestresponse'),
        ),
        migrations.AddIndex(
            model_name='memberrequest',
            index=models.Index(fields=['area', 'status'], name='item_reques_area_id_30a29b_idx'),
        ),
        migrations.AddIndex(
            model_name='memberrequest',
            index=models.Index(fields=['member', 'status'], name='item_reques_member__7e9671_idx'),
        ),
    ]
