# Generated by Django 6.1 on 2026-10-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('registration', 'Registration'), ('subscription_payment', 'Subscription payment'), ('claim', 'Claim'), ('delivery', 'Delivery'), ('withdrawal', 'Withdrawal'), ('complaint', 'Complaint'), ('security', 'Security'), ('offer', 'Offer'), ('announcement', 'Announcement')], max_length=30),
        ),
    ]
