# Generated by Django 6.1 on 2026-09-01 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryjob',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_jobs', to='riders.rider'),
        ),
        migrations.AddField(
            model_name='deliveryotp',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='deliveries.deliveryjob'),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='deliveries.deliveryjob'),
        ),
        migrations.AddField(
            model_name='riderearning',
            name='delivery_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='earning', to='deliveries.deliveryjob'),
        ),
        migrations.AddField(
            model_name='riderearning',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='riders.rider'),
        ),
        migrations.AddIndex(
            model_name='deliveryjob',
            index=models.Index(fields=['status', 'dropoff_area'], name='deliveries__status_41efa8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryjob',
            index=models.Index(fields=['rider', 'status'], name='deliveries__rider_i_0a2307_idx'),
        ),
    ]
