# Generated by Django 6.1 on 2026-09-11 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_riskevent'),
        ('deliveries', '0002_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_time', models.DateTimeField()),
                ('max_packages', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('destination_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.area')),
                ('origin_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.area')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_routes', to='riders.rider')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='deliveries.sharedroute'),
        ),
        migrations.AddIndex(
            model_name='sharedroute',
            index=models.Index(fields=['status', 'origin_area', 'destination_area'], name='deliveries__status_4ac163_idx'),
        ),
    ]
